### ISSUE TITLE
[Enigma] Именование

### ISSUE THREAD

**Issue by pavel-b-novikov** [timofeigladkikh/nsudotnet#4]
Заколебали уже. Ну не используется camelCase в дотнете.

**Comment by timofeigladkikh** [comment]
Исправить и задача будет принята?

**Comment by timofeigladkikh** [comment]
Или есть ещё какие-то недочеты?

**Comment by pavel-b-novikov** [comment]
Что самое интересное, нет. Все остальное в порядке.

**Comment by timofeigladkikh** [comment]
Исправил.
